name: Build and upload to PyPI

# Build on every published release
on: [push, pull_request]
 
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Need to be PIP517 build in order to avoid setuptools bug - https://github.com/pypa/cibuildwheel/issues/813
        # I dunno enough about the work involved in that - sorry!
        # os: [ubuntu-latest, windows-latest, macos-11, macos-latest]
          os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
        # I can't get windows tests to work, but at least here's linux testing the built wheels
          CIBW_BEFORE_TEST_LINUX: mkdir -p ~/examples/samples && cp -R {project}/examples/samples/* ~/examples/samples/
          CIBW_TEST_REQUIRES: pytest
          CIBW_ARCHS_MACOS: 'x86_64 arm64'
          CIBW_BUILD: 'cp39-* cp310-* cp311-*'
          CIBW_TEST_COMMAND_LINUX: "pytest {project}/tests"


      - uses: actions/upload-artifact@v2
        with:
          name: pypi_artifacts
          path: ./wheelhouse/*.whl

